### ISSUE TITLE
Create a table supported OP codes

### ISSUE THREAD

**Issue by alexnorell** [LogicAnalyzer/documentation#20]
Can we get a table of the op codes?

**Comment by johntumath** [comment]
I will write the documentation for the Controller and insert a table in it.

**Comment by johntumath** [comment]
OPCODE | Description | Command (Following Four Bits)
--------------------- | ----------------------------- | -------------------------------------------------------------------------------------------
0x00 | Reset | Doesn't Matter
0x01 | Arm Trigger | Doesn't Matter
0x02 | Query ID | Doesn't Matter
0x04 | Query Metadata | Doesn't Matter
0x05 | Finish Now (TBD) | Doesn't Matter
0x07 | Poll/Query Analyzer State (TBD) | TBD
0x08 | Return Capture Data (TBD) | Doesn't Matter
0x80 | Set Sample Rate | 24 bit value for DIVIDER see https://github.com/LogicAnalyzer/documentation/blob/master/fpga/modules/sampler/sampler.md
0x81 | Set Read/Delay Count | "Command [31:16] is the number of READ samples to take, Command[15:0] is the number of delay samples."
0xC0 | Set Basic Trigger Mask(TBD) | Not yet implemented.
0xC1 | Set Basic Trigger Value | "command[15:8] enables channels 7-0 for falling edge detection |  command [7:0] enables channels 7-0 for rising edge detection |  both rising and falling supported."
